# Generated by Django 4.1.10 on 2024-12-27 05:53
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '화살표',
                'verbose_name_plural': '화살표',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='카테고리 이름', max_length=255)),
                ('description', models.TextField(help_text='카테고리 설명')),
                ('icon', models.CharField(help_text='카테고리 아이콘', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='맵 이름', max_length=255)),
                ('description', models.TextField(help_text='맵 설명')),
                ('icon_image', models.CharField(help_text='아이콘 이미지', max_length=255)),
                ('background_image', models.CharField(help_text='배경 이미지', max_length=255)),
                ('subscriber_count', models.BigIntegerField(db_index=True, default=0, help_text='구독자 수')),
                ('view_count', models.BigIntegerField(db_index=True, default=0, help_text='조회수')),
                ('is_private', models.BooleanField(default=True, help_text='나만의 Map 여부')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='작성자 ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '맵',
                'verbose_name_plural': '맵',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Map 에 보이는 Node 명칭', max_length=255)),
                ('title', models.CharField(help_text='Node 상세 페이지의 제목', max_length=255)),
                ('description', models.TextField()),
                ('background_image', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='관리자의 활성화 여부')),
                ('position_x', models.FloatField(db_index=True)),
                ('position_y', models.FloatField(db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nodes', to='map.map')),
            ],
            options={
                'verbose_name': '노드',
                'verbose_name_plural': '노드',
            },
        ),
        migrations.CreateModel(
            name='NodeCompleteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='해금 규칙 이름', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='complete_rules', to='map.map')),
                ('node', models.ForeignKey(help_text='타겟 Node ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='complete_rules', to='map.node')),
            ],
            options={
                'verbose_name': 'Node 해금 규칙',
                'verbose_name_plural': 'Node 해금 규칙',
            },
        ),
        migrations.CreateModel(
            name='NodeCompletedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='해금된 시각')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_completed_histories', to='map.map')),
                ('member', models.ForeignKey(help_text='해금한 사용자', on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_completed_histories', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(help_text='해금된 Node', on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_completed_histories', to='map.node')),
                ('node_complete_rule', models.ForeignKey(help_text='해금 규칙', on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_completed_histories', to='map.nodecompleterule')),
            ],
            options={
                'verbose_name': '노드 해금 이력',
                'verbose_name_plural': '노드 해금 이력',
            },
        ),
        migrations.CreateModel(
            name='MapCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='map_categories', to='map.category')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='map_categories', to='map.map')),
            ],
            options={
                'verbose_name': '맵 카테고리',
                'verbose_name_plural': '맵 카테고리',
            },
        ),
        migrations.CreateModel(
            name='ArrowProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resolved', models.BooleanField(default=False, help_text='해결 여부')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='해결된 시각', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrow', models.ForeignKey(help_text='진행 중인 Arrow', on_delete=django.db.models.deletion.DO_NOTHING, related_name='progresses', to='map.arrow')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrow_progresses', to='map.map')),
                ('member', models.ForeignKey(help_text='진행 중인 사용자', on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrow_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arrow 진행상태',
                'verbose_name_plural': 'Arrow 진행상태',
            },
        ),
        migrations.AddField(
            model_name='arrow',
            name='end_node',
            field=models.ForeignKey(help_text='타겟 Node', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ending_arrows', to='map.node'),
        ),
        migrations.AddField(
            model_name='arrow',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrows', to='map.map'),
        ),
        migrations.AddField(
            model_name='arrow',
            name='node_complete_rule',
            field=models.ForeignKey(help_text='타겟 Node 해금 규칙', on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrows', to='map.nodecompleterule'),
        ),
    ]
