# Generated by Django 4.1.10 on 2024-12-27 05:53
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrow',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Arrow 해결 조건을 가진 문제', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrows', to='question.question'),
        ),
        migrations.AddField(
            model_name='arrow',
            name='start_node',
            field=models.ForeignKey(help_text='시작 Node', on_delete=django.db.models.deletion.DO_NOTHING, related_name='starting_arrows', to='map.node'),
        ),
    ]
