# Generated by Django 4.1.10 on 2024-12-30 08:32
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='categories',
            field=models.ManyToManyField(help_text='맵 카테고리', related_name='maps', through='map.MapCategory', to='map.category'),
        ),
        migrations.AlterField(
            model_name='map',
            name='created_by',
            field=models.ForeignKey(help_text='생성자', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_maps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='map',
            name='is_private',
            field=models.BooleanField(default=False, help_text='비공개 여부'),
        ),
    ]
