# Generated by Django 4.1.10 on 2025-01-30 00:48
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_node_height_node_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('daily', '일별'), ('monthly', '월별')], help_text='인기 맵 타입', max_length=255)),
                ('subscriber_count', models.BigIntegerField(db_index=True, default=0, help_text='데이터 생성 시 구독자 수')),
                ('view_count', models.BigIntegerField(db_index=True, default=0, help_text='데이터 생성 시 조회 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='popular_maps', to='map.map')),
            ],
            options={
                'verbose_name': '인기 맵',
                'verbose_name_plural': '인기 맵',
            },
        ),
    ]
