# Generated by Django 4.1.10 on 2025-01-30 00:50
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_popularmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularmap',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
