# Generated by Django 4.1.10 on 2025-01-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_popularmap_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='background_image',
            field=models.CharField(help_text='배경 이미지', max_length=2048),
        ),
        migrations.AlterField(
            model_name='map',
            name='icon_image',
            field=models.CharField(help_text='아이콘 이미지', max_length=2048),
        ),
        migrations.AlterField(
            model_name='node',
            name='background_image',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
