# Generated by Django 4.1.10 on 2025-02-02 01:41
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_map_background_image_alter_map_icon_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(help_text='카테고리 아이콘', max_length=2048),
        ),
    ]
