# Generated by Django 4.1.10 on 2025-02-05 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
        ('map', '0008_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecompletedhistory',
            name='map_play',
            field=models.ForeignKey(blank=True, help_text='맵 플레이', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_completed_histories', to='play.mapplay'),
        ),
        migrations.AddField(
            model_name='nodecompletedhistory',
            name='map_play_member',
            field=models.ForeignKey(blank=True, help_text='맵 플레이 멤버', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_completed_histories', to='play.mapplaymember'),
        ),
    ]
