# Generated by Django 4.1.10 on 2025-02-04 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_mapsubscription_updated_at'),
        ('map', '0008_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecompletedhistory',
            name='map_subscription',
            field=models.ForeignKey(blank=True, help_text='맵 구독', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_completed_histories', to='subscription.mapsubscription'),
        ),
    ]
