# Generated by Django 4.1.10 on 2025-02-13 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_mapplaybanned_invite_code'),
        ('map', '0009_nodecompletedhistory_map_play_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrowprogress',
            name='map_play_member',
            field=models.ForeignKey(blank=True, help_text='맵 플레이 멤버', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrow_progresses', to='play.mapplaymember'),
        ),
    ]
