# Generated by Django 4.1.10 on 2025-02-04 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_mapsubscriptionmember_alter_mapsubscription_options_and_more'),
        ('map', '0009_nodecompletedhistory_map_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecompletedhistory',
            name='map_subscription_member',
            field=models.ForeignKey(blank=True, help_text='맵 구독 멤버', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_completed_histories', to='subscription.mapsubscriptionmember'),
        ),
        migrations.AlterField(
            model_name='nodecompletedhistory',
            name='map',
            field=models.ForeignKey(help_text='맵', on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_completed_histories', to='map.map'),
        ),
        migrations.AlterField(
            model_name='nodecompletedhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일시'),
        ),
    ]
