# Generated by Django 4.1.10 on 2025-02-14 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_arrowprogress_map_play_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodecompletedhistory',
            name='map_play',
        ),
    ]
