# Generated by Django 4.1.10 on 2025-03-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_remove_nodecompletedhistory_map_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(default=True, help_text='관리자의 활성화 여부'),
        ),
    ]
