# Generated by Django 4.1.10 on 2025-04-20 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_remove_map_view_count_remove_popularmap_view_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrow',
            name='end_node',
        ),
    ]
