# Generated by Django 4.1.10 on 2025-04-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_remove_arrow_end_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrow',
            name='question',
        ),
    ]
