# Generated by Django 4.1.10 on 2025-02-01 00:50
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_create_admin_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
