# Generated by Django 4.1.10 on 2024-12-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='question_types',
        ),
    ]
