# Generated by Django 4.1.10 on 2025-01-18 03:18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_rename_question_type_question_question_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfile',
            name='name',
            field=models.CharField(blank=True, help_text='파일 이름', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userquestionanswerfile',
            name='name',
            field=models.CharField(blank=True, help_text='파일 이름', max_length=255, null=True),
        ),
    ]
