# Generated by Django 4.1.10 on 2025-02-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_mapplaybanned_invite_code'),
        ('question', '0003_questionfile_name_userquestionanswerfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionanswer',
            name='map_play_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_answers', to='play.mapplaymember'),
        ),
    ]
