# Generated by Django 4.1.10 on 2025-02-20 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_remove_nodecompletedhistory_map_play'),
        ('question', '0004_userquestionanswer_map_play_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='arrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='map.arrow'),
        ),
    ]
