# Generated by Django 4.1.10 on 2025-02-05 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0008_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='플레이 제목', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('created_by', models.ForeignKey(help_text='생성자', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_map_plays', to=settings.AUTH_USER_MODEL)),
                ('map', models.ForeignKey(help_text='맵', on_delete=django.db.models.deletion.DO_NOTHING, related_name='plays', to='map.map')),
            ],
            options={
                'verbose_name': '맵 플레이',
                'verbose_name_plural': '맵 플레이',
            },
        ),
        migrations.CreateModel(
            name='MapPlayMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', '참여자'), ('admin', '관리자')], help_text='역할', max_length=20)),
                ('deactivated', models.BooleanField(default=False, help_text='비활성화 여부')),
                ('deactivated_reason', models.CharField(blank=True, choices=[('self_deactivated', '자발적 탈퇴'), ('banned', '추방')], help_text='비활성화 사유', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('map_play', models.ForeignKey(help_text='맵 플레이', on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='play.mapplay')),
                ('member', models.ForeignKey(help_text='멤버', on_delete=django.db.models.deletion.DO_NOTHING, related_name='map_play_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '맵 플레이 멤버',
                'verbose_name_plural': '맵 플레이 멤버',
            },
        ),
        migrations.CreateModel(
            name='MapPlayMemberRoleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_role', models.CharField(choices=[('participant', '참여자'), ('admin', '관리자')], help_text='이전 역할', max_length=20)),
                ('new_role', models.CharField(choices=[('participant', '참여자'), ('admin', '관리자')], help_text='새로운 역할', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='변경 사유', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('changed_by', models.ForeignKey(help_text='역할 변경한 admin', on_delete=django.db.models.deletion.DO_NOTHING, related_name='map_play_member_role_change_histories', to=settings.AUTH_USER_MODEL)),
                ('map_play_member', models.ForeignKey(help_text='맵 플레이 멤버', on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_histories', to='play.mapplaymember')),
            ],
            options={
                'verbose_name': '맵 플레이 멤버 역할 변경 이력',
                'verbose_name_plural': '맵 플레이 멤버 역할 변경 이력',
            },
        ),
        migrations.CreateModel(
            name='MapPlayInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='초대 코드', max_length=50, unique=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='최대 사용 횟수 (null인 경우 무제한)', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0, help_text='현재 사용 횟수')),
                ('expired_at', models.DateTimeField(blank=True, db_index=True, help_text='만료일시', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('created_by', models.ForeignKey(help_text='초대 코드 생성자', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_map_play_invite_codes', to=settings.AUTH_USER_MODEL)),
                ('map_play', models.ForeignKey(help_text='맵 플레이', on_delete=django.db.models.deletion.DO_NOTHING, related_name='invite_codes', to='play.mapplay')),
            ],
            options={
                'verbose_name': '맵 플레이 초대 코드',
                'verbose_name_plural': '맵 플레이 초대 코드',
            },
        ),
        migrations.CreateModel(
            name='MapPlayBanned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_reason', models.TextField(help_text='추방 사유')),
                ('banned_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='추방 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('banned_by', models.ForeignKey(help_text='추방한 admin', on_delete=django.db.models.deletion.DO_NOTHING, related_name='map_play_ban_histories', to=settings.AUTH_USER_MODEL)),
                ('map_play', models.ForeignKey(help_text='맵 플레이', on_delete=django.db.models.deletion.DO_NOTHING, related_name='banned_members', to='play.mapplay')),
                ('member', models.ForeignKey(help_text='추방된 멤버', on_delete=django.db.models.deletion.DO_NOTHING, related_name='map_play_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '맵 플레이 추방',
                'verbose_name_plural': '맵 플레이 추방',
            },
        ),
    ]
