# Generated by Django 4.1.10 on 2025-02-06 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapplaybanned',
            name='invite_code',
            field=models.ForeignKey(blank=True, help_text='사용한 초대 코드', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banned_members', to='play.mapplayinvitecode'),
        ),
    ]
