# Generated by Django 4.1.10 on 2025-02-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_mapplaybanned_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapplaymember',
            name='deactivated_reason',
            field=models.CharField(blank=True, choices=[('self_deactivated', '자발적 탈퇴'), ('unsubscribe', '구독 탈퇴'), ('banned', '추방')], help_text='비활성화 사유', max_length=20, null=True),
        ),
    ]
