# Generated by Django 4.1.10 on 2025-02-18 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0004_alter_member_profile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='디바이스 토큰', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], help_text='디바이스 타입', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('guest', models.ForeignKey(help_text='토큰 소유자', on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_tokens', to='member.guest')),
            ],
            options={
                'verbose_name': '디바이스 토큰',
                'verbose_name_plural': '디바이스 토큰',
            },
        ),
        migrations.CreateModel(
            name='PushHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='알림 제목', max_length=255)),
                ('body', models.TextField(help_text='알림 내용')),
                ('data', models.JSONField(blank=True, help_text='추가 데이터', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='발송일시')),
                ('is_success', models.BooleanField(default=False, help_text='발송 성공 여부')),
                ('error_message', models.TextField(blank=True, help_text='실패 사유', null=True)),
                ('device_token', models.ForeignKey(help_text='수신 디바이스', on_delete=django.db.models.deletion.DO_NOTHING, related_name='push_histories', to='push.devicetoken')),
                ('guest', models.ForeignKey(help_text='수신자', on_delete=django.db.models.deletion.DO_NOTHING, related_name='push_histories', to='member.guest')),
            ],
            options={
                'verbose_name': '푸시 발송 이력',
                'verbose_name_plural': '푸시 발송 이력',
            },
        ),
    ]
