# Generated by Django 4.1.10 on 2025-02-18 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0004_userquestionanswer_map_play_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionAnswerPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_question_answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='question.userquestionanswer')),
            ],
        ),
    ]
