# Generated by Django 4.1.10 on 2025-05-04 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_alter_mapplaymember_deactivated_reason'),
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushMapPlayMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_type', models.CharField(choices=[('REMINDER', '리마인더')], help_text='푸시 타입', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('map_play_member', models.ForeignKey(help_text='맵 플레이 멤버', on_delete=django.db.models.deletion.DO_NOTHING, related_name='push_map_play_members', to='play.mapplaymember')),
            ],
            options={
                'verbose_name': '푸시 맵 플레이 멤버',
                'verbose_name_plural': '푸시 맵 플레이 멤버',
            },
        ),
    ]
