# Generated by Django 4.1.10 on 2025-05-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0002_pushmapplaymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushmapplaymember',
            name='push_date',
            field=models.DateField(blank=True, help_text='푸시 발송일', null=True),
        ),
        migrations.AddField(
            model_name='pushmapplaymember',
            name='push_time',
            field=models.TimeField(blank=True, help_text='푸시 발송시간', null=True),
        ),
    ]
