# Generated by Django 4.1.10 on 2025-05-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_pushmapplaymember_push_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushmapplaymember',
            name='remind_info',
            field=models.TextField(blank=True, help_text='추가 리마인드', null=True),
        ),
    ]
