# Generated by Django 4.1.10 on 2025-05-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0004_pushmapplaymember_remind_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushmapplaymember',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 여부'),
        ),
    ]
