-- Arrow 생성
INSERT INTO map_arrow (map_id, start_node_id, end_node_id, node_complete_rule_id, question_id, is_deleted, created_at, updated_at)
VALUES
-- Self-referencing Arrows (with Questions)
(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Java 설치와 환경설정'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Java 설치와 환경설정'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Java 설치와 환경설정')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'Java 개발 환경 구축하기'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Java 기초 문법'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Java 기초 문법'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Java 기초 문법')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'Java 기초 문법 실습'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '객체지향 기초'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '객체지향 기초'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '객체지향 기초')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = '객체지향 프로그래밍 실습'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '컬렉션 프레임워크'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '컬렉션 프레임워크'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '컬렉션 프레임워크')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = '컬렉션 프레임워크 활용'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '예외처리'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '예외처리'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '예외처리')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = '예외 처리 구현하기'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '스트림 API'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '스트림 API'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '스트림 API')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = '스트림 API 실습'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'SQL 기초'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'SQL 기초'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'SQL 기초')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'SQL 기초 실습'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JDBC'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JDBC'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JDBC')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'JDBC 프로그래밍'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '서블릿/JSP'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '서블릿/JSP'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '서블릿/JSP')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = '서블릿/JSP 실습'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Core'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Core'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Core')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'Spring Core 실습'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring MVC'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring MVC'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring MVC')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'Spring MVC 구현'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JPA 기초'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JPA 기초'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JPA 기초')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'JPA 시작하기'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'REST API 기초'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'REST API 기초'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'REST API 기초')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'REST API 시작하기'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Data JPA'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Data JPA'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Data JPA')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'Spring Data JPA 실습'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'API 문서화'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'API 문서화'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'API 문서화')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'API 문서화 실습'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Boot'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Boot'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Boot')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'Spring Boot 실습'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JPA/Hibernate'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JPA/Hibernate'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JPA/Hibernate')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'JPA/Hibernate 실습'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Security'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Security'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Security')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'Spring Security 구현'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'REST API'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'REST API'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'REST API')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = 'REST API 개발'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '테스트 코드'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '테스트 코드'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '테스트 코드')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = '테스트 코드 작성'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '성능 최적화'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '성능 최적화'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '성능 최적화')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = '성능 최적화 실습'),
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '배포와 운영'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '배포와 운영'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '배포와 운영')),
 (SELECT id FROM question_question WHERE map_id = 2 AND title = '배포 환경 구축'),
 false, NOW(), NOW()),

-- 기본 학습 경로 Arrows (without Questions)
-- Java 기초 → Java 심화
(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Java 설치와 환경설정'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Java 기초 문법'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Java 기초 문법')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Java 기초 문법'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '객체지향 기초'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '객체지향 기초')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '객체지향 기초'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '컬렉션 프레임워크'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '컬렉션 프레임워크')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '컬렉션 프레임워크'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '예외처리'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '예외처리')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '예외처리'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '스트림 API'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '스트림 API')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '스트림 API'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'SQL 기초'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'SQL 기초')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'SQL 기초'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JDBC'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JDBC')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JDBC'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '서블릿/JSP'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '서블릿/JSP')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '서블릿/JSP'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Core'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Core')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Core'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring MVC'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring MVC')),
 NULL,
 false, NOW(), NOW()),

-- Spring Boot로 가는 세 가지 경로
-- 1. Spring MVC 경로
(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring MVC'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Boot'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Boot')),
 NULL,
 false, NOW(), NOW()),

-- 2. JPA 경로
(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JPA 기초'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Data JPA'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Data JPA')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Data JPA'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Boot'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Boot')),
 NULL,
 false, NOW(), NOW()),

-- 3. REST API 경로
(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'REST API 기초'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'API 문서화'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'API 문서화')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'API 문서화'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Boot'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Boot')),
 NULL,
 false, NOW(), NOW()),

-- Spring Boot 이후 경로
(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Boot'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JPA/Hibernate'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JPA/Hibernate')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'JPA/Hibernate'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Security'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Security')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'Spring Security'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'REST API'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = 'REST API')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = 'REST API'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '테스트 코드'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '테스트 코드')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '테스트 코드'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '성능 최적화'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '성능 최적화')),
 NULL,
 false, NOW(), NOW()),

(2,
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '성능 최적화'),
 (SELECT id FROM map_node WHERE map_id = 2 AND name = '배포와 운영'),
 (SELECT id FROM map_nodecompleterule WHERE map_id = 2 AND node_id = (SELECT id FROM map_node WHERE map_id = 2 AND name = '배포와 운영')),
 NULL,
 false, NOW(), NOW()); 